# -*- coding: utf-8 -*-
"""for h10 and without kde, updated threshold,pit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fr0L1Jjt_UC2r8ln1LkjJlJGXmm8Kivg
"""

import os
import argparse
import pandas as pd
import numpy as np

# all your imports: arch, copulae, pyvinecopulib, etc.
from arch import arch_model
from scipy.stats import t, norm
from itertools import combinations
from scipy.stats import kstest
import pyvinecopulib as pv

from itertools import combinations
from tqdm.auto import trange
# =======================
# GLOBAL REPRODUCIBILITY
# =======================
import os

import random
GLOBAL_SEED = 42
random.seed(GLOBAL_SEED)
np.random.seed(GLOBAL_SEED)
os.environ["PYTHONHASHSEED"] = str(GLOBAL_SEED)




# Python RNG


# NumPy RNG


# Ensure deterministic hashing


# pyvinecopulib RNG (CRITICAL)
import pyvinecopulib as pv




def fit_garch_gaussian(returns):

    amm = arch_model(
        returns,
        vol="GARCH",
        p=1, o=1, q=1,          # ✅ GJR-GARCH
        dist="normal",
        mean="ARX",
        lags=1,
        rescale=False
    )
    ress = amm.fit(disp="off")

    params = ress.params

    # ---- AR(1) mean ----
    ar_param = [k for k in params.index if k.endswith("[1]")][0]
    phi_1 = params[ar_param]
    const_mu = params["Const"]

    r_t = returns.iloc[-1]
    muu = const_mu + phi_1 * r_t   # μ_{t+1}

    # ---- standardized residuals ----
    sigma_tt = ress.conditional_volatility
    zz = ress.resid / sigma_tt

    # ---- one-step volatility forecast ----
    forecastt = ress.forecast(horizon=1)
    sigma_forecast = np.sqrt(forecastt.variance.values[-1, 0])

    # ---- GJR parameters for horizon simulation ----
    garch_params = {
        "omega": params["omega"],
        "alpha": params["alpha[1]"],
        "beta":  params["beta[1]"],
        "gamma": params.get("gamma[1]", 0.0),   # ✅ leverage
        "phi":   phi_1,
        "const": const_mu
    }

    return muu, sigma_tt, zz, ress, sigma_forecast, garch_params

# -----------------------------
# Step 2. Standardized residuals → uniforms
# -----------------------------
def to_uniforms(z):
    eps = 1e-10
    return np.clip(norm.cdf(z), eps, 1 - eps)

# -----------------------------
# Step 3. Fit Gaussian Vine Copula
# -----------------------------
def fit_gaussian_vine(U):
    controls = pv.FitControlsVinecop(family_set=[pv.BicopFamily.gaussian], selection_criterion="loglik")
    vinee = pv.Vinecop.from_data(U, controls=controls)
    return vinee

# -----------------------------
# Step 4. Simulate from Vine
# -----------------------------




# -----------------------------
# Step 5. Portfolio VaR & ES using forecasted volatilities
# -----------------------------
def simulate_portfolio_var_es_horizon_gaussian(
    vine_model,
    mu0_map,
    sigma0_map,
    garch_params_map,
    weights,
    n_paths=10000,
    horizon=10,
    alpha=0.05,
    window_seed=42
):
    """
    Gaussian baseline:
    - Same vine dependence
    - Gaussian residuals
    - Plain GARCH(1,1) recursion (NO GJR)
    - Horizon-h cumulative VaR / ES
    """

    stocks = list(mu0_map.keys())
    d = len(stocks)

    # =====================================================
    # (A) ---- STORAGE ----
    # =====================================================
    port_paths = np.zeros((n_paths, horizon))

    mu_paths    = {s: np.full(n_paths, mu0_map[s]) for s in stocks}
    sigma_paths = {s: np.full(n_paths, sigma0_map[s]) for s in stocks}
    eps_last    = {s: np.zeros(n_paths) for s in stocks}

    # =====================================================
    # (B) ---- PATHWISE SIMULATION ----
    # =====================================================
    for h in range(horizon):

        # 1) simulate copula uniforms
        U = vine_model.simulate(n_paths, seeds=[window_seed + h])

        # lambda_hat (copula-only, computed once)


        # 2) uniforms → Gaussian residuals
        Z = norm.ppf(np.clip(U, 1e-10, 1 - 1e-10))

        daily_returns = np.zeros((n_paths, d))

        # 3) returns + GARCH recursion
        for j, s in enumerate(stocks):

            mu    = mu_paths[s]
            sigma = sigma_paths[s]
            eps   = Z[:, j]

            r = mu + sigma * eps
            daily_returns[:, j] = r
            k=sigma*eps

            # GARCH(1,1) update
            p = garch_params_map[s]
            omega = p["omega"]
            alpha_g = p["alpha"]
            beta = p["beta"]
            gamma = p["gamma"]

            indicator = (k < 0).astype(float)

            sigma2_next = (
                omega
                + alpha_g * k**2
                + beta  * sigma**2
                + gamma * indicator * k**2
                )

            sigma_paths[s] = np.sqrt(np.maximum(sigma2_next, 1e-10))

            mu_paths[s] = p["const"] + p["phi"] * r

        # 4) portfolio aggregation
        port_paths[:, h] = daily_returns @ weights

    # =====================================================
    # (C) ---- HORIZON-h VaR / ES ----
    # =====================================================
    port_h = port_paths.sum(axis=1)

    VaR_h = np.quantile(port_h, alpha)
    ES_h  = port_h[port_h <= VaR_h].mean()

    return np.array([VaR_h]), np.array([ES_h]), port_paths



# ... paste all other function definitions here ...
# e.g. standardresiduals, thresholdselection, pitformation, etc.
def standardresiduals(returns):
    import pandas as pd


    standardized_resid_dict = {}
    mu_t = {}
    sigma_t = {}
    garch_param_map = {}
    nu_t = {}



    for stock in returns.columns:

        try:
            model = arch_model(returns[stock], vol='GARCH',o=1, p=1, q=1,
                              dist='t', mean='ARX', lags=1, rescale=False)
            result = model.fit(disp="off")

            ar_param = [key for key in result.params.index if key.endswith("[1]")][0]
            phi_1 = result.params[ar_param]
            mu = result.params['Const'] + phi_1 * returns[stock].shift(1)

            sigma = result.conditional_volatility

            standardized_resid_dict[stock] = result.std_resid


            # Parameters for simulation
            params = result.params

            const_mu = params['Const']

            omega = params['omega']
            alpha = params['alpha[1]']
            gamma = params['gamma[1]']
            beta = params['beta[1]']
            r_t = returns[stock].iloc[-1]
            mu_tt = mu.iloc[-1]
            sigma_tt = sigma.iloc[-1]
            mu_t_plus_1 = const_mu + phi_1 * r_t
            epsilon_t = r_t - mu_tt
            indicator = 1.0 if epsilon_t < 0 else 0.0  # GJR indicator
            sigma_t_plus_1 = np.sqrt(max(omega + alpha * epsilon_t**2 +
                                    beta * sigma_tt**2 +
                                    gamma * indicator * epsilon_t**2,1e-10))
            mu_t[stock] = mu_t_plus_1
            sigma_t[stock] = sigma_t_plus_1
            garch_param_map[stock] = {
                            "omega": omega,
                            "alpha": alpha,
                            "beta":  beta,
                            "gamma": gamma,
                            "phi":   phi_1,
                            "const": const_mu
                 }
            nu = result.params["nu"]
            nu_t[stock] = nu
        except Exception as e:
            print(f"Model failed for {stock}: {e}")
    return standardized_resid_dict,mu_t,sigma_t,garch_param_map,nu_t
def nostandardresiduals(returns):
    import pandas as pd

    from statsmodels.tsa.arima.model import ARIMA
    from arch import arch_model
    p=1
    q=1


    standardized_resid_dict = {}
    mu_t = {}
    sigma_t = {}

    for stock in returns.columns:
        try:
            y = returns[stock].dropna()

            # ---------------- STEP 1: Fit ARMA(p,q) mean model ----------------
            arma_model = ARIMA(y, order=(p, 0, q))
            arma_res = arma_model.fit()

            # Get fitted mean (μ_t) and residuals (ε_t)
            mu_series = arma_res.fittedvalues
            resid = arma_res.resid.dropna()

            # ---------------- STEP 2: Fit GJR-GARCH(1,1) volatility model ----------------
            garch_model = arch_model(
                resid,
                vol='GARCH',
                p=1, q=1, o=1,
                dist='t',
                rescale=True
            )
            garch_res = garch_model.fit(disp='off')

            # In-sample conditional volatility
            sigma_series = garch_res.conditional_volatility
            std_resid = garch_res.std_resid
            standardized_resid_dict[stock] = std_resid

            # ---------------- STEP 3: One-step-ahead forecast ----------------
            params = arma_res.params
            const_mu = params.get('const', 0.0)
            phi_1 = params.get('ar.L1', 0.0)
            theta_1 = params.get('ma.L1', 0.0)

            # Latest observed values
            r_t = y.iloc[-1]
            mu_t_last = mu_series.iloc[-1]
            eps_t = resid.iloc[-1]

            # Conditional mean forecast (includes lagged return & lagged error)
            mu_t_plus_1 = const_mu + phi_1 * r_t + theta_1 * eps_t

            # GARCH params
            par = garch_res.params
            omega = par['omega']
            alpha = par['alpha[1]']
            beta = par['beta[1]']
            gamma = par.get('gamma[1]', 0.0)

            sigma_t_last = sigma_series.iloc[-1]
            indicator = 1.0 if eps_t < 0 else 0.0

            sigma_t_plus_1 = np.sqrt(
                max(omega +
                    alpha * eps_t**2 +
                    beta * sigma_t_last**2 +
                    gamma * indicator * eps_t**2, 1e-10)
            )

            mu_t[stock] = mu_t_plus_1
            sigma_t[stock] = sigma_t_plus_1

        except Exception as e:
            print(f"Model failed for {stock}: {e}")

    return standardized_resid_dict, mu_t, sigma_t
def thresholdselection(dat,window_seed):

        import pandas as pd
        from scipy.stats import genpareto, kstest

        def anderson_darling_statistic(data, c, scale):
            data_sorted = np.sort(data)
            n = len(data_sorted)
            cdf_vals = genpareto.cdf(data_sorted, c, loc=0, scale=scale)
            cdf_vals = np.clip(cdf_vals, 1e-8, 1-1e-8)
            i = np.arange(1, n+1)
            ad_stat = -n - np.sum((2*i - 1) * (np.log(cdf_vals) + np.log(1 - cdf_vals[::-1])) / n)
            return ad_stat

        def bootstrap_ad_pvalue(exceedances, c, scale, n_bootstrap=300, random_state=None):


              n = len(exceedances)
              rng = np.random.default_rng(random_state)


              # observed AD using already-fitted parameters
              obs_ad = anderson_darling_statistic(exceedances, c, scale)

              boot_stats = []
              for _ in range(n_bootstrap):
                  # simulate from fitted GPD

                  sim_data = genpareto.rvs(c, loc=0, scale=scale, size=n, random_state=rng)



                  stat = anderson_darling_statistic(sim_data, c, scale)
                  boot_stats.append(stat)

              return np.mean(np.array(boot_stats) >= obs_ad)

        def auto_gpd_threshold(
            data,
            tail='upper',
            percentiles=np.linspace(80, 99.5, 50),
            min_exceedances=100,
            significance_level=0.05,
            n_bootstrap=300,
            random_state=None
        ):
            """
            Fully automated GPD threshold selection.
            Returns: dict with threshold, shape, scale, p-values, and number of exceedances.
            """
            stability_tol=0.20
            stability_window=6
            data = np.asarray(data)
            if tail == 'lower':
                data = -data
                sign = -1
            else:
                sign = 1

            thresholds = np.percentile(data, percentiles)
            results = []
            for u in thresholds:
                    exceedances = data[data > u] - u

                    xi, loc, sigma = genpareto.fit(exceedances, floc=0)
                    ks_stat, ks_p = kstest(exceedances, 'genpareto', args=(xi, loc, sigma))
                    ad_p = bootstrap_ad_pvalue(exceedances, xi, sigma, n_bootstrap=n_bootstrap, random_state=window_seed)
                    results.append({
                        "Threshold (u)": sign*u,
                        "Shape": xi,
                        "Scale": sigma,
                        'Loc':loc,
                        "KS_p": ks_p,
                        "AD_p": ad_p,
                        "Num_Exceedances": len(exceedances)
                    })

            if not results:
                raise ValueError("No valid thresholds found.")

            df = pd.DataFrame(results)
            df["xi_std"] = df["Shape"].rolling(
                stability_window, center=True
            ).std()

            df["sigma_std"] = df["Scale"].rolling(
                stability_window, center=True
            ).std()

            df["xi_mean"] = df["Shape"].rolling(
                stability_window, center=True
            ).mean()

            df["sigma_mean"] = df["Scale"].rolling(
                stability_window, center=True
            ).mean()

            # Relative stability (better than absolute std)
            df["xi_rel"] = df["xi_std"] / (np.abs(df["xi_mean"]) + 1e-8)
            df["sigma_rel"] = df["sigma_std"] / (np.abs(df["sigma_mean"]) + 1e-8)

            df["stable"] = (
                (df["xi_rel"] < stability_tol) &
                (df["sigma_rel"] < stability_tol))

            # Statistically valid rows
            valid = df[
        (df["KS_p"] > significance_level) &
        (df["AD_p"] > significance_level) &
        (df["stable"])
               ]
            fallback = False
            reason = None

            if not valid.empty:
                if (valid["Num_Exceedances"] >= min_exceedances).any():
                    best_row = valid[valid["Num_Exceedances"] >= min_exceedances].sort_values("Num_Exceedances", ascending=False).iloc[0]
                else:
                    # Sparse tail
                    best_row = valid.sort_values("Num_Exceedances", ascending=False).iloc[0]
                    fallback = True
                    reason = "sparse"
            else:
                # Invalid EVT
                best_row = df.sort_values("Num_Exceedances", ascending=False).iloc[0]
                fallback = True
                reason = "invalid"


            best_row["Fallback"] = fallback
            best_row["FallbackReason"] = reason
            return best_row.to_dict()

        # For all stocks:
        thresholds_summary = []
        for stock in dat.columns:

            for tail in ['upper', 'lower']:
                try:
                    data = dat[stock].dropna().values
                    result = auto_gpd_threshold(data, tail=tail)
                    result.update({"Stock": stock, "Tail": tail})
                    thresholds_summary.append(result)
                except Exception as e:
                    print(f"Failed for {stock} – {tail} tail: {e}")
        return thresholds_summary
def pitformation(df, gpd_df, nu_t):
    import numpy as np
    from scipy.stats import genpareto, gaussian_kde, t
    import warnings
    warnings.filterwarnings("ignore")

    uniform_transformed = {}

    for stock in df.columns:
        resid = df[stock].dropna().values
        n_total = len(resid)

        nu = nu_t[stock]
        c  = np.sqrt((nu - 2) / nu)

        lower_row = gpd_df.query("Stock == @stock and Tail == 'lower'").iloc[0]
        upper_row = gpd_df.query("Stock == @stock and Tail == 'upper'").iloc[0]

        lower_thresh = lower_row["Threshold (u)"]
        upper_thresh = upper_row["Threshold (u)"]
        params_lower = (lower_row["Shape"], lower_row["Loc"], lower_row["Scale"])
        params_upper = (upper_row["Shape"], upper_row["Loc"], upper_row["Scale"])

        lower_fallback = lower_row.get("Fallback", False)
        upper_fallback = upper_row.get("Fallback", False)

        p_lower  = len(resid[resid < lower_thresh]) / n_total
        p_upper  = len(resid[resid > upper_thresh]) / n_total
        p_center = 1.0 - (p_lower + p_upper)

        kde_data = resid[(resid >= lower_thresh) & (resid <= upper_thresh)]
        kde = gaussian_kde(kde_data)

        cdf_lo = kde.integrate_box_1d(-np.inf, lower_thresh)
        cdf_hi = kde.integrate_box_1d(-np.inf, upper_thresh)
        Z = max(cdf_hi - cdf_lo, 1e-12)

        Ft_lower = t.cdf(lower_thresh / c, df=nu)
        Ft_upper = t.cdf(upper_thresh / c, df=nu)

        def kde_cdf_trunc(x, _cdf_lo=cdf_lo, _Z=Z):
            return (kde.integrate_box_1d(-np.inf, x) - _cdf_lo) / _Z

        def hybrid_cdf(x,
                       _p_lower=p_lower, _p_upper=p_upper, _p_center=p_center,
                       _lower_thresh=lower_thresh, _upper_thresh=upper_thresh,
                       _params_lower=params_lower, _params_upper=params_upper,
                       _lower_fallback=lower_fallback, _upper_fallback=upper_fallback,
                       _nu=nu, _c=c,
                       _Ft_lower=Ft_lower, _Ft_upper=Ft_upper):

            if x < _lower_thresh:
                if not _lower_fallback:
                    z = _lower_thresh - x
                    return _p_lower * (1.0 - genpareto.cdf(z, c=_params_lower[0], loc=0, scale=_params_lower[2]))
                else:
                    return _p_lower * t.cdf(x / _c, df=_nu) / _Ft_lower

            elif x <= _upper_thresh:
                return _p_lower + _p_center * kde_cdf_trunc(x)

            else:
                if not _upper_fallback:
                    z = x - _upper_thresh
                    return (1.0 - _p_upper) + _p_upper * genpareto.cdf(z, c=_params_upper[0], loc=0, scale=_params_upper[2])
                else:
                    return (1.0 - _p_upper) + _p_upper * (
                        (t.cdf(x / _c, df=_nu) - _Ft_upper) / (1.0 - _Ft_upper)
                    )

        sort_idx = np.argsort(resid)
        u_sorted = np.array([hybrid_cdf(x) for x in resid[sort_idx]])
        u_sorted = np.maximum.accumulate(u_sorted)
        u_sorted = np.clip(u_sorted, 1e-10, 1 - 1e-10)

        u = np.empty_like(u_sorted)
        u[sort_idx] = u_sorted

        uniform_transformed[stock] = u

    return uniform_transformed
def inverse(data, gpd_df, nu_t):
    import numpy as np
    from scipy.stats import genpareto, gaussian_kde, t
    from scipy.interpolate import interp1d

    inverse_cdf_funcs = {}
    clip_eps = 1e-10

    for stock in data.columns:
        resid = data[stock].dropna().values
        n_total = len(resid)

        nu = nu_t[stock]
        c  = np.sqrt((nu - 2) / nu)

        lower_row = gpd_df.query("Stock == @stock and Tail == 'lower'").iloc[0]
        upper_row = gpd_df.query("Stock == @stock and Tail == 'upper'").iloc[0]

        lower_thresh = lower_row["Threshold (u)"]
        upper_thresh = upper_row["Threshold (u)"]
        params_lower = (lower_row["Shape"], lower_row["Loc"], lower_row["Scale"])
        params_upper = (upper_row["Shape"], upper_row["Loc"], upper_row["Scale"])

        lower_fallback = lower_row.get("Fallback", False)
        upper_fallback = upper_row.get("Fallback", False)

        p_lower  = len(resid[resid < lower_thresh]) / n_total
        p_upper  = len(resid[resid > upper_thresh]) / n_total
        p_center = 1.0 - (p_lower + p_upper)

        kde_data = resid[(resid >= lower_thresh) & (resid <= upper_thresh)]
        kde = gaussian_kde(kde_data)

        cdf_lo = kde.integrate_box_1d(-np.inf, lower_thresh)
        cdf_hi = kde.integrate_box_1d(-np.inf, upper_thresh)
        Z = max(cdf_hi - cdf_lo, 1e-12)

        x_grid = np.linspace(kde_data.min(), kde_data.max(), 700)
        k_grid = np.array([
            (kde.integrate_box_1d(-np.inf, x) - cdf_lo) / Z
            for x in x_grid
        ])
        k_grid = np.maximum.accumulate(k_grid)
        k_grid = np.clip(k_grid, clip_eps, 1.0 - clip_eps)

        _, uniq = np.unique(k_grid, return_index=True)

        inv_kde = interp1d(
            k_grid[uniq], x_grid[uniq],
            bounds_error=False,
            fill_value=(kde_data.min(), kde_data.max())
        )

        Ft_lower = t.cdf(lower_thresh / c, df=nu)
        Ft_upper = t.cdf(upper_thresh / c, df=nu)

        def _make_ppf(inv_kde_,
                      p_lower_, p_upper_, p_center_,
                      lower_thresh_, upper_thresh_,
                      params_lower_, params_upper_,
                      lower_fallback_, upper_fallback_,
                      nu_, c_, Ft_lower_, Ft_upper_):

            def hybrid_ppf(u_array):
                u_array = np.asarray(u_array, dtype=float)
                result  = np.empty_like(u_array)

                for i, u in enumerate(u_array):
                    u = float(np.clip(u, clip_eps, 1.0 - clip_eps))

                    try:
                        if u < p_lower_:
                            if not lower_fallback_:
                                q = np.clip(1.0 - u / p_lower_, clip_eps, 1.0 - clip_eps)
                                result[i] = lower_thresh_ - genpareto.ppf(q, *params_lower_)
                            else:
                                q = np.clip(u * Ft_lower_ / p_lower_, clip_eps, Ft_lower_ - clip_eps)
                                result[i] = t.ppf(q, df=nu_) * c_

                        elif u <= 1.0 - p_upper_:
                            k = np.clip((u - p_lower_) / p_center_, clip_eps, 1.0 - clip_eps)
                            result[i] = float(inv_kde_(k))

                        else:
                            if not upper_fallback_:
                                q = np.clip((u - (1.0 - p_upper_)) / p_upper_, clip_eps, 1.0 - clip_eps)
                                result[i] = upper_thresh_ + genpareto.ppf(q, *params_upper_)
                            else:
                                q = Ft_upper_ + (u - (1.0 - p_upper_)) / p_upper_ * (1.0 - Ft_upper_)
                                q = np.clip(q, Ft_upper_ + clip_eps, 1.0 - clip_eps)
                                result[i] = t.ppf(q, df=nu_) * c_

                    except Exception as e:
                        print(f"[ERROR] stock={stock} u={u} exception: {e}")
                        result[i] = np.nan

                return result

            return hybrid_ppf

        inverse_cdf_funcs[stock] = _make_ppf(
            inv_kde,
            p_lower, p_upper, p_center,
            lower_thresh, upper_thresh,
            params_lower, params_upper,
            lower_fallback, upper_fallback,
            nu, c, Ft_lower, Ft_upper
        )

    return inverse_cdf_funcs
def christoffersen_independence_test(violations):
    """
    Christoffersen (1998) Independence Test (LR_IND)

    Tests whether VaR violations are independent over time
    (i.e., no clustering).

    Parameters
    ----------
    violations : array-like
        0/1 sequence where 1 = violation

    Returns
    -------
    LR_ind : float
        Likelihood ratio statistic
    p_value : float
        p-value from Chi-square(1)
    """


    from scipy.stats import chi2

    v = np.asarray(violations, dtype=int)

    # Transition counts
    n00 = n01 = n10 = n11 = 0
    for i in range(1, len(v)):
        prev, curr = v[i-1], v[i]
        if prev == 0 and curr == 0: n00 += 1
        elif prev == 0 and curr == 1: n01 += 1
        elif prev == 1 and curr == 0: n10 += 1
        elif prev == 1 and curr == 1: n11 += 1

    # Transition probabilities
    pi_01 = n01 / (n00 + n01) if (n00 + n01) > 0 else 0
    pi_11 = n11 / (n10 + n11) if (n10 + n11) > 0 else 0
    pi = (n01 + n11) / (n00 + n01 + n10 + n11)

    eps = 1e-12  # numerical safeguard

    # Log-likelihood under independence (H0)
    ll0 = (
        (n01 + n11) * np.log(pi + eps) +
        (n00 + n10) * np.log(1 - pi + eps)
    )

    # Log-likelihood under Markov alternative (H1)
    ll1 = (
        n01 * np.log(pi_01 + eps) +
        n00 * np.log(1 - pi_01 + eps) +
        n11 * np.log(pi_11 + eps) +
        n10 * np.log(1 - pi_11 + eps)
    )

    LR_ind = -2 * (ll0 - ll1)
    p_value = 1 - chi2.cdf(LR_ind, df=1)

    return LR_ind, p_value


def dq_test1(returns, VaR, alpha=0.05, lags=1):

    from scipy.stats import chi2

    returns = np.asarray(returns)
    VaR = np.asarray(VaR)

    T = len(returns)

    # Hit sequence (centered)
    hit = (returns < VaR).astype(float) - alpha

    # -----------------------------
    # Design matrix: intercept + lagged hits
    # -----------------------------
    X = np.ones((T, 1))  # intercept

    for k in range(1, lags + 1):
        lagged = np.roll(hit, k)
        lagged[:k] = 0.0
        X = np.column_stack((X, lagged))

    # Trim initial observations
    hit = hit[lags:]
    X = X[lags:, :]

    # -----------------------------
    # DQ statistic
    # -----------------------------
    XtX_inv = np.linalg.pinv(X.T @ X)

    dq_stat = (hit.T @ X @ XtX_inv @ X.T @ hit) / (alpha * (1 - alpha))

    # Degrees of freedom = number of lagged hits
    df = X.shape[1]

    p_value = 1 - chi2.cdf(dq_stat, df)

    return dq_stat, p_value
def dq_test4(returns, VaR, alpha=0.05, lags=4):

    from scipy.stats import chi2

    returns = np.asarray(returns)
    VaR = np.asarray(VaR)

    T = len(returns)

    # Hit sequence (centered)
    hit = (returns < VaR).astype(float) - alpha

    # -----------------------------
    # Design matrix: intercept + lagged hits
    # -----------------------------
    X = np.ones((T, 1))  # intercept

    for k in range(1, lags + 1):
        lagged = np.roll(hit, k)
        lagged[:k] = 0.0
        X = np.column_stack((X, lagged))

    # Trim initial observations
    hit = hit[lags:]
    X = X[lags:, :]

    # -----------------------------
    # DQ statistic
    # -----------------------------
    XtX_inv = np.linalg.pinv(X.T @ X)

    dq_stat = (hit.T @ X @ XtX_inv @ X.T @ hit) / (alpha * (1 - alpha))

    # Degrees of freedom = number of lagged hits
    df = X.shape[1]

    p_value = 1 - chi2.cdf(dq_stat, df)

    return dq_stat, p_value

# 2. Acerbi–Szekely Unconditional ES Test
def es_unconditional_test(X_obs, VaR, ES, alpha=0.05, nSim=10000, rng=None):




    X_obs = np.asarray(X_obs)
    VaR = np.asarray(VaR)
    ES = np.asarray(ES)
    T = len(X_obs)

    if rng is None:
        rng = np.random.default_rng(GLOBAL_SEED)

    # -------------------------------------------------
    # 1. Convert RETURNS -> LOSSES
    # -------------------------------------------------
    L = -X_obs
    VaR_L = -VaR
    ES_L = -ES

    # -------------------------------------------------
    # 2. Observed test statistic
    # -------------------------------------------------
    I = (L >= VaR_L).astype(float)

    stat = (1 / (T * alpha)) * np.sum((L * I) / ES_L) - 1

    # -------------------------------------------------
    # 3. Simulate null distribution
    # -------------------------------------------------
    sim_stats = np.zeros(nSim)

    for b in range(nSim):

        U = rng.uniform(size=T)
        Z = rng.exponential(scale=1.0, size=T)

        I_sim = (U < alpha).astype(float)

        # Under null:
        # Tail losses = ES_L * Exp(1)
        L_sim = np.where(
            I_sim == 1,
            ES_L * Z,
            0.0
        )

        sim_stats[b] = (1 / (T * alpha)) * np.sum((L_sim * I_sim) / ES_L) - 1

    # -------------------------------------------------
    # 4. p-value (left tail test)
    # -------------------------------------------------
    p_value = np.mean(sim_stats <= stat)
    crit_val = np.percentile(sim_stats, 100 * alpha)

    return stat, crit_val, p_value


# 3. Full Backtest Function
from scipy.stats import chi2


def kupiec_lr_test(violations, alpha):
    """
    Kupiec (1995) Unconditional Coverage Test (LR_UC)
    """
    violations = np.asarray(violations, dtype=int)
    n = len(violations)
    x = violations.sum()

    # Degenerate cases
    if x == 0 or x == n:
        return np.nan, np.nan

    phat = x / n

    logL0 = (n - x) * np.log(1 - alpha) + x * np.log(alpha)
    logL1 = (n - x) * np.log(1 - phat) + x * np.log(phat)

    LR_uc = -2 * (logL0 - logL1)
    p_value = 1 - chi2.cdf(LR_uc, df=1)

    return LR_uc, p_value

def fz_score(y, var, es, alpha):
    """
    Fissler–Ziegel (2016) joint VaR–ES scoring rule (FZ0)
    Lower is better.
    """
    y = np.asarray(y)
    var = np.asarray(var)
    es = np.asarray(es)

    eps = 1e-12
    es_safe = np.minimum(es, -eps)

    I = (y <= var).astype(float)

    term1 = -(1.0 / (alpha * es_safe)) * I * (var - y)
    term2 = var / es_safe
    term3 = np.log(-es_safe) - 1.0

    return term1 + term2 + term3
def backtest_var_es(actual_returns,
                    var_series,
                    es_series,
                    var_level=0.05,
                    nSim=10000):
    """
    Backtest VaR and ES using Kupiec, Christoffersen, and Acerbi–Szekely tests.
    Inputs: np.ndarray or list for all arguments.
    """

    actual_returns = np.asarray(actual_returns)
    var_series = np.asarray(var_series)
    es_series = np.asarray(es_series)

    # 1. VaR Violations
    violations = actual_returns < var_series
    n_violations = violations.sum()
    n = len(actual_returns)

    # 2. Kupiec Test (Unconditional Coverage)
    count = n_violations
    kupiec_stat, kupiec_p = kupiec_lr_test(violations, var_level)


    # 3. Christoffersen Test (Conditional Coverage)
    christ_stat, christ_p = christoffersen_independence_test(violations)


    # 4. ES Accuracy (Acerbi–Szekely Unconditional Test)
    rng = np.random.default_rng(GLOBAL_SEED)

    es_stat, es_crit, es_p = es_unconditional_test(
    X_obs=actual_returns,
    VaR=var_series,
    ES=es_series,
    alpha=var_level,
    nSim=nSim,rng=rng)
    dq_stat1, dq_p1 = dq_test1(
    returns=actual_returns,
    VaR=var_series,
    alpha=var_level,
    lags=1)
    dq_stat4, dq_p4 = dq_test4(
    returns=actual_returns,
    VaR=var_series,
    alpha=var_level,
    lags=4)

    fz_losses = fz_score(
        y=actual_returns,
        var=var_series,
        es=es_series,
        alpha=var_level
    )

    mean_fz = np.mean(fz_losses)
    median_fz = np.median(fz_losses)

    # 5. Mean Absolute ES Error (for violations)
    actual_losses = actual_returns[violations]
    es_predicted = es_series[violations]
    empirical_es_loss = actual_returns[violations].mean()
    mae_es = np.abs(actual_losses - es_predicted).mean()
    empirical_es_loss = actual_returns[violations].mean()
    empirical_es_loss_percent = (np.exp(empirical_es_loss/100) - 1) * 100




    # Print results
    print(f"\n📊 Backtest Results (VaR Level: {int(var_level * 100)}%)")
    print(f"-------------------------------------------")
    print(f"VaR violations:              {n_violations} / {n} ({n_violations/n:.2%})")
    print(f"Kupiec Test p-value:         {kupiec_p:.4f}")
    print(f"Christoffersen p-value:      {christ_p:.4f}")
    print(f"DQ Test stat:                {dq_stat1:.4f}")
    print(f"DQ Test p-value:             {dq_p1:.4f}")
    print(f"DQ Test stat:                {dq_stat4:.4f}")
    print(f"DQ Test p-value:             {dq_p4:.4f}")
    print(f"Acerbi–Szekely ES stat:      {es_stat:.4f}")
    print(f"Acerbi–Szekely crit value:   {es_crit}")
    print(f"Acerbi–Szekely ES p-value:   {es_p}")
    print(f"Mean Absolute ES Error:      {mae_es:.4f}")
    print(f"Empirical ES in % : {empirical_es_loss:.2f}%")
    aa=n_violations/n

    return {
        "VaR violations":aa,
        'violations':n_violations,
        'n':n,

        "kupiec_p": kupiec_p,
        "christoffersen_p": christ_p,
        "dq_stat1": dq_stat1,
        "dq_p1": dq_p1,
        "dq_stat4": dq_stat4,
        "dq_p4": dq_p4,
        "acerbi_szekely_stat": es_stat,
        "acerbi_szekely_crit": es_crit,
        "acerbi_szekely_p": es_p,
        "mae_es": mae_es,
        "empirical_es_loss": empirical_es_loss,
        "mean_fz_loss": mean_fz,
        "median_fz_loss": median_fz
    }
def cvm_1d(x):
    x = np.sort(x)
    n = len(x)
    i = np.arange(1, n + 1)
    return (1 / (12 * n)) + np.sum((x - (2 * i - 1) / (2 * n)) ** 2)

def global_cvm_statistic(R):
            # R: (n,d) Rosenblatt outputs
            return np.mean([cvm_1d(R[:, j]) for j in range(R.shape[1])])

def rosenblatt_gof_pvalue(vine_model, U, n_bootstrap=1000, window_seed=None):
    if window_seed is None:
        window_seed = GLOBAL_SEED

    R_obs = vine_model.rosenblatt(U)
    obs_stat = global_cvm_statistic(R_obs)

    n = U.shape[0]
    boot_stats = np.empty(n_bootstrap)

    for b in range(n_bootstrap):
        sim_U = vine_model.simulate(n, seeds=[window_seed + b])
        sim_R = vine_model.rosenblatt(sim_U)
        boot_stats[b] = global_cvm_statistic(sim_R)

    p_value = np.mean(boot_stats >= obs_stat)
    return obs_stat, p_value, boot_stats

        # ---- 2) Empirical pairwise lambda (average across unique pairs) ----


def empirical_pairwise_lambda_avg(U, q=0.05):
    if U.ndim == 3 and U.shape[1] == 1:
        U = U[:, 0, :]   # (n_paths, d)

    n, d = U.shape
    pairs = list(combinations(range(d), 2))
    vals = []

    for i, j in pairs:
        joint = np.sum((U[:, i] < q) & (U[:, j] < q))
        vals.append(joint / (n * q))

    return np.mean(vals), vals, pairs


def model_lambda_bootstrap_from_vine(vine_model, q=0.05, n_sim=500, B=1000, window_seed=None):
    if window_seed is None:
        window_seed = GLOBAL_SEED

    lam_vals = np.empty(B)
    for b in range(B):
        samp = vine_model.simulate(n_sim, seeds=[window_seed + b])
        lam_vals[b], _, _ = empirical_pairwise_lambda_avg(samp, q=q)

    lo = np.percentile(lam_vals, 2.5)
    hi = np.percentile(lam_vals, 97.5)
    return lam_vals.mean(), (lo, hi), lam_vals



        # ---- 3) Simulate next-day VaR & ES from vine using your inverse/mu/sigma ----
def simulate_portfolio_var_es_horizon(
    vine_model,
    inverse_cdf_funcs,
    mu0_map,
    sigma0_map,
    garch_params_map,
    weights,
    n_paths=10000,
    horizon=10,
    alpha=0.05,
    window_seed=42,
    q_lambda=0.05

):
    """
    Full pathwise Monte Carlo for h-day VaR / ES
    PLUS correct copula-based lambda_hat for model selection
    """

    stocks = list(mu0_map.keys())
    d = len(stocks)

    # =====================================================
    # (A) ---- LAMBDA HAT (COPULA-ONLY, HORIZON-FREE) ----
    # =====================================================


    # =====================================================
    # (B) ---- HORIZON h PATHWISE SIMULATION ----
    # =====================================================
    port_paths = np.zeros((n_paths, horizon))

    mu_paths = {s: np.full(n_paths, mu0_map[s]) for s in stocks}
    sigma_paths = {s: np.full(n_paths, sigma0_map[s]) for s in stocks}


    for h in range(horizon):

        # ---- 1) simulate copula uniforms (risk only) ----
        U = vine_model.simulate(n_paths, seeds=[window_seed+h])
        if h==0:

          lam_hat, _, _ = empirical_pairwise_lambda_avg(U, q=q_lambda)

        # ---- 2) uniforms → residuals ----
        Z = np.zeros_like(U)
        for j, s in enumerate(stocks):
            Z[:, j] = inverse_cdf_funcs[s](U[:, j])

        # ---- 3) returns + GARCH update ----
        daily_returns = np.zeros((n_paths, d))

        for j, s in enumerate(stocks):

            mu = mu_paths[s]
            sigma = sigma_paths[s]
            eps = Z[:, j]

            r = mu + sigma * eps
            k=sigma*eps
            daily_returns[:, j] = r

            p = garch_params_map[s]
            omega, alpha_g, beta, gamma = (
                p["omega"], p["alpha"], p["beta"], p["gamma"]
            )

            indicator = (k < 0).astype(float)
            sigma2_next = (
                omega
                + alpha_g * k**2
                + beta * sigma**2
                + gamma * indicator * k**2
            )

            sigma_paths[s] = np.sqrt(np.maximum(sigma2_next, 1e-10))

            mu_paths[s] = p["const"] + p["phi"] * r

        # ---- 4) portfolio aggregation ----
        port_paths[:, h] = daily_returns @ weights

    # =====================================================
    # (C) ---- HORIZON h VaR / ES ----
    # =====================================================
    port_h = port_paths.sum(axis=1)

    VaR_h = np.quantile(port_h, alpha)
    ES_h  = port_h[port_h <= VaR_h].mean()

    # ✅ SAME FORMAT AS YOUR PIPELINE
    return np.array([VaR_h]), np.array([ES_h]), port_paths, lam_hat

def count_vine_parameters(vine):
    k = 0
    for tree in vine.pair_copulas:
        for pc in tree:
            k += len(pc.parameters)
    return k

def main(input_csv, output_dir):
    # Read return data

    import pandas as pd
    from scipy.stats import t
    from scipy.stats import norm

    os.makedirs(output_dir, exist_ok=True)
    df = pd.read_csv(input_csv, index_col=0, parse_dates=True)
    df = df.dropna(axis=0)
    df = df * 100


    split_date = "2011-04-26"
    global train_df, test_df
    train_df = df[df.index > split_date]
    test_df = df[df.index >= split_date]




    # Assume test_df is your test set DataFrame (dates as index, columns as asset returns)
    # Assume model_info is a dict with keys as stock names and values as dicts containing 'mu_tt', 'sigma_tt', 'nu'

    window_size = 1000
    step_size = 10
    var_level = 0.05
    weights = np.array([0.5,0.5])  # Adjust as needed
    stock_names = train_df.columns.tolist()
    actual_returns=[]
    dates=[]
    L=100
    var_results = []
    var_hist = []
    var_normal = []
    var_t = []
    var_garch = []

    es_hist = []
    es_normal = []
    es_t = []
    es_garch = []

    es_results=[]
    var_vine_gauss=[]
    es_vine_gauss=[]
    ks_results=[]

    # keep historical OOS ES losses





    fz_loss_hist_t = []
    fallback_log = []
    fz_loss_hist_b = []

    def es_loss_fz_scalar(y, VaR, ES, alpha=0.05):


              eps = 1e-12  # numerical safety
              ES_safe = min(ES, -eps)

              I = float(y <= VaR)

              term1 = -(1.0 / (alpha * ES_safe)) * I * (VaR - y)
              term2 = VaR / ES_safe
              term3 = np.log(-ES_safe) - 1.0

              return term1 + term2 + term3




    selection_log = []
    hill_summary = []
    all_gpd_dfs = []

    forecastt = 10

    for start in range(0, len(train_df) - window_size - forecastt, step_size):

        end = start + window_size

        # ----------------------------
        # Training window: up to time t
        # ----------------------------
        window_returns = train_df.iloc[start:end]

        # ----------------------------
        # Portfolio history (used for HS, parametric fits, etc.)
        # ----------------------------
        portfolio_returns = window_returns @ weights

        # ----------------------------
        # Realized horizon-10 return: t+1 ... t+10
        # ----------------------------
        future_window = train_df.iloc[end : end + forecastt]
        actual_ret = (future_window @ weights).sum()

        window_date = train_df.index[end + forecastt - 1]

        actual_returns.append(actual_ret)
        dates.append(window_date)


        # ==========================================================
        # 1. Historical Simulation
        # ==========================================================
        window_seed = GLOBAL_SEED + start

        # ==========================================================
        # 1. Historical Simulation (horizon-aware)
        # ==========================================================
        if forecastt == 1:
            var_hist_val = float(np.quantile(portfolio_returns, var_level))
            tail_h       = portfolio_returns[portfolio_returns <= var_hist_val]
            es_hist_val  = float(tail_h.mean()) if len(tail_h) > 0 else var_hist_val

        else:
            n_boot = 10_000
            rng_hs = np.random.default_rng(window_seed + 1)

            daily = portfolio_returns.values
            n     = len(daily)
            h     = forecastt

            # ✅ Overlapping blocks (moving block bootstrap)
            block_starts = np.arange(n - h + 1)

            # Safety check (rare, but robust)
            if len(block_starts) == 0:
                var_hist_val = np.nan
                es_hist_val  = np.nan
            else:
                chosen = rng_hs.choice(block_starts, size=n_boot, replace=True)

                # cumulative h-day returns
                cum_boot = np.array([
                    daily[s:s+h].sum() for s in chosen
                ])

                var_hist_val = float(np.quantile(cum_boot, var_level))
                tail_b       = cum_boot[cum_boot <= var_hist_val]
                es_hist_val  = float(tail_b.mean()) if len(tail_b) > 0 else var_hist_val

        var_hist.append(var_hist_val)
        es_hist.append(es_hist_val)

        # ==========================================================
        # 2. Parametric Normal (horizon-aware)
        # ==========================================================
        m    = portfolio_returns.mean()
        sigm = portfolio_returns.std(ddof=1)

        if forecastt == 1:
            var_norm_val = m + sigm * norm.ppf(var_level)
            es_norm_val  = m - sigm * norm.pdf(norm.ppf(var_level)) / var_level

        else:
            m_h          = m * forecastt
            sigm_h       = sigm * np.sqrt(forecastt)
            var_norm_val = m_h + sigm_h * norm.ppf(var_level)
            es_norm_val  = m_h - sigm_h * norm.pdf(norm.ppf(var_level)) / var_level

        var_normal.append(var_norm_val)
        es_normal.append(es_norm_val)

        # ==========================================================
        # 3. Parametric Student-t (horizon-aware)
        # ==========================================================
        # t.fit() fits: X ~ loc + scale * T(nu)
        # where T(nu) is a raw t-variate with variance nu/(nu-2)
        # so sigm_mle is the scale for raw t shocks, NOT the std dev.
        # Therefore do NOT standardise z_t when using sigm_mle.
        try:
            nu_mle, mu_mle, sigm_mle = t.fit(portfolio_returns, floc=m)
            nu     = float(np.clip(nu_mle, 2.01, 50.0))
            sigm_t = float(sigm_mle)

        except Exception:
            # Fallback: kurtosis-based nu estimate
            # kurt = 6/(nu-4) => nu = 6/kurt + 4
            excess_kurt = float(portfolio_returns.kurt())
            if excess_kurt > 0:
                nu = max(6.0 / excess_kurt + 4.0, 2.01)
            else:
                nu = 30.0
            # sample sigm assumes unit-variance shocks, so convert to
            # t-scale: scale = std * sqrt((nu-2)/nu)
            sigm_t = sigm * np.sqrt((nu - 2) / nu)

        if forecastt == 1:
            q_t        = t.ppf(var_level, df=nu)
            var_t_val  = m + sigm_t * q_t
            pdf_val    = t.pdf(q_t, df=nu)
            es_scaling = (nu + q_t**2) / (nu - 1)
            es_t_val   = m - sigm_t * (pdf_val / var_level) * es_scaling

        else:
            n_sim_t   = 10_000
            rng_t     = np.random.default_rng(window_seed + 2)
            # raw t shocks, no standardisation — sigm_t (MLE scale) is already
            # calibrated for raw t variance = nu/(nu-2)
            z_t       = rng_t.standard_t(df=nu, size=(n_sim_t, forecastt))
            cum_t     = (m + sigm_t * z_t).sum(axis=1)
            var_t_val = float(np.quantile(cum_t, var_level))
            tail_t    = cum_t[cum_t <= var_t_val]
            es_t_val  = float(tail_t.mean()) if len(tail_t) > 0 else var_t_val

        var_t.append(var_t_val)
        es_t.append(es_t_val)

        # ==========================================================
        # 4. GARCH(1,1)-Normal (horizon-aware)
        # — plain symmetric GARCH, Gaussian innovations (traditional)
        # — intentionally simpler than robust GJR-GARCH-t model
        # ==========================================================
        try:
            am_garch  = arch_model(
                portfolio_returns,
                vol='Garch', p=1, q=1,
                dist='gaussian',
                rescale=False
            )
            res_garch = am_garch.fit(disp='off')
            mu_garch  = res_garch.params['mu']

            if forecastt == 1:
                fcast         = res_garch.forecast(horizon=1)
                sigma_garch   = np.sqrt(fcast.variance.values[-1, 0])
                var_garch_val = mu_garch + sigma_garch * norm.ppf(var_level)
                es_garch_val  = mu_garch - sigma_garch * (
                    norm.pdf(norm.ppf(var_level)) / var_level
                )

            else:
                omega_g     = res_garch.params['omega']
                alpha_g     = res_garch.params['alpha[1]']
                beta_g      = res_garch.params['beta[1]']
                sigma2_last = res_garch.conditional_volatility.iloc[-1] ** 2

                n_sim   = 10_000
                rng     = np.random.default_rng(window_seed)
                z_sim   = rng.standard_normal((n_sim, forecastt))
                sigma2  = np.full(n_sim, sigma2_last)
                cum_ret = np.zeros(n_sim)

                for hh in range(forecastt):
                    sigma_h  = np.sqrt(np.maximum(sigma2, 1e-10))
                    r_h      = mu_garch + sigma_h * z_sim[:, hh]
                    cum_ret += r_h
                    eps_h    = sigma_h * z_sim[:, hh]
                    sigma2   = omega_g + alpha_g * eps_h**2 + beta_g * sigma2

                var_garch_val = float(np.quantile(cum_ret, var_level))
                tail_losses   = cum_ret[cum_ret <= var_garch_val]
                es_garch_val  = float(tail_losses.mean()) if len(tail_losses) > 0 else var_garch_val

        except Exception as e:
            print(f"[GARCH] Failed at window {window_date}: {e}")
            var_garch_val = np.nan
            es_garch_val  = np.nan

        var_garch.append(var_garch_val)
        es_garch.append(es_garch_val)




        returns=window_returns
        import pandas as pd

        import pyvinecopulib as pv
        mu_mapp = {}
        sigma_forecast_map = {}
        U_list = []
        gaussgarch_param_map = {}

        # Fit GARCH and get standardized residuals + forecasted volatility
        for stock in train_df.columns:
            muu, sigma_tt, z, res, sigma_forecast,garch_params = fit_garch_gaussian(returns[stock])
            mu_mapp[stock] = muu
            sigma_forecast_map[stock] = sigma_forecast
            U_list.append(to_uniforms(z))
            gaussgarch_param_map[stock] = garch_params

        UU = np.vstack(U_list).T  # shape (T, d)

        # Fit Gaussian Vine Copula
        vine_gauss = fit_gaussian_vine(UU)

        # Simulate from Vine





        # Compute portfolio VaR & ES (tomorrow)
        varvine_gauss, esvine_gauss, sims = simulate_portfolio_var_es_horizon_gaussian(
    vine_gauss,
    mu_mapp,
    sigma_forecast_map,
    gaussgarch_param_map,
    weights,
    n_paths=10000,
    horizon=10,
    alpha=var_level,
    window_seed=window_seed
)

        var_vine_gauss.append(float(varvine_gauss[0]))
        es_vine_gauss.append(float(esvine_gauss[0]))
        standardized_resid_dict,mu_t,sigma_t,garch_param_map,nu_t=standardresiduals(returns)

        # Save residuals
        standardized_resid_df = pd.DataFrame(standardized_resid_dict).iloc[1:]


        thresholds_summary=thresholdselection(standardized_resid_df,window_seed)
        gpd_df = pd.DataFrame(thresholds_summary)
        for _, row in gpd_df.iterrows():
            fallback_log.append({
                "Date": window_date,
                "Stock": row["Stock"],
                "Tail": row["Tail"],
                "Fallback": row["Fallback"],
                "Reason": row.get("FallbackReason", None)
            })
        all_gpd_dfs.append(gpd_df)





        uniform_transformed=pitformation(standardized_resid_df,gpd_df,nu_t)
        # --- Save result ---




        pit_df = pd.DataFrame(uniform_transformed, index=standardized_resid_df.index)




        # Load PIT-transformed data

        U = pit_df.to_numpy()

        for stock in pit_df.columns:
                  e = pit_df[stock].dropna()
                  stat, pval = kstest(e, 'uniform')
                  ks_results.append({
                      'Date': window_date,
                      'Stock': stock,
                      'KS_statistic': stat,
                      'p_value': pval
                  })




        inverse_cdf_funcs=inverse(standardized_resid_df,gpd_df,nu_t)
        # ---------- Insert this inside your rolling-window loop AFTER pit_df & inverse_cdf_funcs exist ----------


        from itertools import combinations
        from tqdm.auto import trange

        # ---- 1) Rosenblatt CvM functions (your original approach) ----


        # ---- 4) Fit two pure-family vines and evaluate them with your Rosenblatt GoF ----
        U = pit_df.to_numpy()
        n, d = U.shape

        # Fit pure-student vine


        controls_student = pv.FitControlsVinecop(family_set=[pv.BicopFamily.student], selection_criterion="loglik")
        vine_student = pv.Vinecop.from_data(U, controls=controls_student)

        # Fit pure-bb7 vine
        controls_bb7 = pv.FitControlsVinecop(family_set=[pv.BicopFamily.bb7], selection_criterion="loglik")
        vine_bb7 = pv.Vinecop.from_data(U, controls=controls_bb7)

        # Compute Rosenblatt CvM p-values using your exact method (smaller bootstraps for speed)
        B_gof = 1000     # increase if you have CPU/time
        obs_t, pval_t, boot_t = rosenblatt_gof_pvalue(vine_student, U, n_bootstrap=B_gof,window_seed=window_seed)
        obs_b, pval_b, boot_b = rosenblatt_gof_pvalue(vine_bb7, U, n_bootstrap=B_gof,window_seed=window_seed)

        # Compute empirical lambda and model lambda bootstraps
        q_lambda = 0.05
        lam_emp_avg, lam_emp_pairs, lam_pairs = empirical_pairwise_lambda_avg(U, q=q_lambda)

        B_lambda = 1000
        lam_t, lam_t_ci, lam_t_boot = model_lambda_bootstrap_from_vine(vine_student, q=q_lambda, n_sim=len(U), B=B_lambda,window_seed=window_seed)
        lam_b, lam_b_ci, lam_b_boot = model_lambda_bootstrap_from_vine(vine_bb7, q=q_lambda, n_sim=len(U), B=B_lambda,window_seed=window_seed)

        # Simulate VaR/ES from each vine (use your inverse_cdf_funcs, mu_t, sigma_t)
        n_paths_sim = 10000
        # --- simulate VaR / ES from copulas ---
        var_t_model, es_t_model, sims_t,lam_t_hat = simulate_portfolio_var_es_horizon(
              vine_model=vine_student,
              inverse_cdf_funcs=inverse_cdf_funcs,
              mu0_map=mu_t,
              sigma0_map=sigma_t,
              garch_params_map=garch_param_map,
              weights=weights,
              n_paths=10000,
              horizon=10,
              alpha=var_level,
              window_seed=window_seed
              )

        var_b_model, es_b_model, sims_b, lam_b_hat = simulate_portfolio_var_es_horizon(
                vine_model=vine_bb7,
                inverse_cdf_funcs=inverse_cdf_funcs,
                mu0_map=mu_t,
                sigma0_map=sigma_t,
                garch_params_map=garch_param_map,
                weights=weights,
                n_paths=n_paths_sim,
                horizon=10,
                alpha=var_level,
                window_seed=window_seed
              )

        # ---- Composite rule (i)-(ii) ----
        def check_criteria(pval, lam_hat, lam_ci, lam_emp, tol=0.05):
            c1 = (pval > 0.05)
            c2 = (
                abs(lam_hat - lam_emp) <= tol
                and lam_ci[0] <= lam_emp <= lam_ci[1]
            )
            return c1, c2

        c_t = check_criteria(pval_t, lam_t_hat, lam_t_ci, lam_emp_avg)
        c_b = check_criteria(pval_b, lam_b_hat, lam_b_ci, lam_emp_avg)

        score_t = int(c_t[0]) + int(c_t[1])
        score_b = int(c_b[0]) + int(c_b[1])

        # ---- (iii) Historical OOS ES loss (NO actual return used) ----


        def compute_aic(loglik, n_params):
             return -2 * loglik + 2 * n_params
        loglik_t = vine_student.loglik()
        k_t = count_vine_parameters(vine_student)
        aic_t = compute_aic(loglik_t, k_t)

        loglik_b = vine_bb7.loglik()
        k_b = count_vine_parameters(vine_bb7)
        aic_b = compute_aic(loglik_b, k_b)

        # ---- model choice ----

        use_fz = len(fz_loss_hist_t) >= L and len(fz_loss_hist_b) >= L

        if score_t > score_b:
            winner = "student"

        elif score_b > score_t:
            winner = "bb7"

        else:
            if use_fz:
    # ---- ES-based selection (meaningful regime) ----
                  mean_fz_t = np.mean(fz_loss_hist_t[-L:])
                  mean_fz_b = np.mean(fz_loss_hist_b[-L:])

                  winner = "student" if mean_fz_t < mean_fz_b else "bb7"

            else:
                # ---- cold / no-violation regime ----
                # use AIC only
                winner = "student" if aic_t < aic_b else "bb7"


        # ---- store chosen forecasts ----
        if winner == "student":
            var_results.append(var_t_model)
            es_results.append(es_t_model)
        else:
            var_results.append(var_b_model)
            es_results.append(es_b_model)


        # Log selection for later analysis
        # update OOS ES loss histories

        fz_loss_hist_t.append(
                es_loss_fz_scalar(
                    actual_ret,
                    float(var_t_model[0]),
                    float(es_t_model[0]),
                    alpha=var_level
                )
            )


        fz_loss_hist_b.append(
                es_loss_fz_scalar(
                    actual_ret,
                    float(var_b_model[0]),
                    float(es_b_model[0]),
                    alpha=var_level
                )
            )


        selection_log.append({
            "Date": window_date, "Winner": winner,
            "gofpval_student": float(pval_t), "gofpval_bb7": float(pval_b),
            "lam_emp": float(lam_emp_avg),
            "actual_returns":float(actual_ret),
            "lam_student": float(lam_t_hat), "lam_student_ci_lo": float(lam_t_ci[0]), "lam_student_ci_hi": float(lam_t_ci[1]),
            "lam_bb7": float(lam_b_hat), "lam_bb7_ci_lo": float(lam_b_ci[0]), "lam_bb7_ci_hi": float(lam_b_ci[1]),
            "es_student": float(es_t_model[0]), "es_bb7": float(es_b_model[0])
        })

        print(f"[{window_date.date()}] Winner: {winner} | p_t={pval_t:.3f} p_b={pval_b:.3f} | lam_emp={lam_emp_avg:.3f} lam_t={lam_t_hat:.3f} lam_b={lam_b_hat:.3f}")

    import pandas as pd

    # Convert selection_log (list of dicts) to DataFrame
    sel_df = pd.DataFrame(selection_log)
    ks_df = pd.DataFrame(ks_results)
    ks_df.to_csv(os.path.join(output_dir, "ks_test_results.csv"), index=False)

    # Save to CSV
    sel_df.to_csv(os.path.join(output_dir, "selection_log.csv"), index=False)
    final_gpd_df = pd.concat(all_gpd_dfs, axis=0)
    final_gpd_df.to_csv(os.path.join(output_dir, "automated_gpd_thresholds.csv"), index=False)

    import pandas as pd
    from statsmodels.stats.proportion import proportions_ztest
    from scipy.stats import chi2
    standardized_resid_df.to_csv(os.path.join(output_dir, "standardized_residuals.csv"))
    pit_df.to_csv(os.path.join(output_dir, "pit_transformed_uniforms.csv"))

    # 1. Christoffersen Test (Conditional Coverage)

    df_results = pd.DataFrame({
    'Date': dates,
    'VaR_Historical': var_hist,
    'ES_Historical': es_hist,
    'VaR_Normal': var_normal,
    'ES_Normal': es_normal,
    'VaR_StudentT': var_t,
    'ES_StudentT': es_t,
    'VaR_VineGaussian': var_vine_gauss,
    'ES_VineGaussian': es_vine_gauss,


    'VaR_GARCH': var_garch,
    'ES_GARCH': es_garch,

    })
    df_results.set_index("Date", inplace=True)


    # ... (rest of your main logic here, as in the notebook, adjusted for script use) ...
    # Save outputs to output_dir as needed
    methods = [
    ("Parametric_t", "VaR_StudentT", "ES_StudentT"),
    ("Historical", "VaR_Historical", "ES_Historical"),
    ("Normal", "VaR_Normal", "ES_Normal"),

    ("GARCH", "VaR_GARCH", "ES_GARCH"),
    ("benchmark", "VaR_VineGaussian", "ES_VineGaussian")

    ]

    results_summary = {}

    for method_name, var_col, es_col in methods:
        var_seriess = df_results[var_col].values
        es_seriess = df_results[es_col].values
        var_seriess = [float(x[0]) if isinstance(x, (np.ndarray, list)) else float(x) for x in var_seriess]
        es_seriess = [float(x[0]) if isinstance(x, (np.ndarray, list)) else float(x) for x in es_seriess]
        print(f"\nRunning backtest for {method_name} method...")
        resultss = backtest_var_es(
            actual_returns=actual_returns,
            var_series=var_seriess,
            es_series=es_seriess,
            var_level=0.05
        )

        results_summary[method_name] = resultss

    # Optionally display/save summary table of test p-values/statistics
    import pandas as pd
    summary_df = pd.DataFrame(results_summary).T
    print("\nBacktest Results Summary for all methods:")
    print(summary_df)

    # You can save summary_df to CSV for your report
    summary_df.to_csv(os.path.join(output_dir, "var_es_backtest_summary.csv"))
    var_results = [float(x[0]) if isinstance(x, (np.ndarray, list)) else float(x) for x in var_results]
    es_results = [float(x[0]) if isinstance(x, (np.ndarray, list)) else float(x) for x in es_results]
    var_es_df = pd.DataFrame({
        "Date": dates,
        "Actual": actual_returns,
        "VaR_5%": var_results,
        "ES_5%": es_results
    })
    var_es_df.set_index("Date", inplace=True)

    var_es_df.to_csv(os.path.join(output_dir, "var_es_results.csv"))




    import pandas as pd

    # Run backtest
    result = backtest_var_es(
        actual_returns = var_es_df["Actual"].values,
        var_series     = var_es_df["VaR_5%"].values,
        es_series      = var_es_df["ES_5%"].values,
        var_level      = 0.05
          # or 5000 if faster execution needed
    )

    # Convert dict → DataFrame
    backtestresultsmodel = pd.DataFrame([result])   # wrap in list to make it a single-row DataFrame

    # Save to CSV
    backtestresultsmodel.to_csv(os.path.join(output_dir, "backtest_results.csv"), index=False)
    fallback_df = pd.DataFrame(fallback_log)
    fallback_df.to_csv(os.path.join(output_dir, "fallback_log.csv"), index=False)

    print("Finished all computations. Results saved.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run advanced VaR-ES model pipeline.")
    parser.add_argument("--input", type=str, required=True, help="Path to input log_returns.csv")
    parser.add_argument("--output_dir", type=str, default="results", help="Output directory for results")
    args = parser.parse_args()

    main(args.input, args.output_dir)